const {chromium}=require('/home/amr/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');const runtime=process.env.VLEX_CRUD_RUNTIME,base=process.env.VLEX_CRUD_BASE;
let checks=0;function check(ok,label){if(!ok)throw Error(label);checks++;}
(async()=>{const browser=await chromium.launchPersistentContext(path.join(runtime,'crud-profile'),{executablePath:'/usr/bin/google-chrome',headless:true,ignoreHTTPSErrors:true,extraHTTPHeaders:{'X-Test-Key':process.env.VLEXPLOSION_TEST_KEY},env:{...process.env,TMPDIR:process.env.VLEX_CRUD_TEMP},args:['--no-sandbox','--disable-breakpad','--disable-crash-reporter','--disable-background-networking','--disable-component-update','--disk-cache-dir='+path.join(runtime,'crud-cache')]});
try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/login');await page.locator('[name="login"]').fill('fiction');await page.locator('[name="password"]').fill('fictional-password');await page.locator('button[type="submit"]').click();await page.waitForURL('**/vinyls');
await page.goto(base+'/vinyls/create');await page.locator('#title').fill('Browser fictional album');await page.locator('[name="authors[]"]').fill('Browser Author');await page.locator('#add-author').click();await page.locator('[name="authors[]"]').last().fill('Browser Second');await page.locator('#producer').fill('Browser Producer');for(const id of ['genre_id','format_id','condition_id','record_label_id','edition_id'])await page.locator('#'+id).selectOption('1');await page.locator('#release_date').selectOption('2020');await page.locator('[name="is_favorite"]').check();await page.locator('#cover').setInputFiles(path.join(runtime,'fixture.png'));await page.locator('#vinyl-form button[type="submit"]').click();await page.waitForURL('**/vinyls?**');const id=new URL(page.url()).searchParams.get('highlight');check(!!id,'create redirects to highlighted record');check((await page.locator('body').textContent()).includes('Vinilo añadido correctamente.'),'truthful creation confirmation');
await page.goto(base+'/vinyls/show?id='+id);check((await page.locator('#vinyl-information').textContent()).includes('Browser Second'),'created authors visible');
await page.goto(base+'/vinyls/edit?id='+id);check(await page.locator('#title').inputValue()==='Browser fictional album','edit existing title');check(await page.locator('[name="authors[]"]').count()===2,'edit authors');check(await page.locator('[name="is_favorite"]').isChecked(),'edit favorite value');await page.locator('#title').fill('Browser edited album');await page.locator('#producer').fill('Browser Edited Producer');await page.locator('[name="authors[]"]').last().fill('Browser Changed');await page.locator('[name="is_desired"]').check();await page.locator('#release_date').selectOption('2021');await page.locator('#vinyl-form button[type="submit"]').click();await page.waitForURL('**/vinyls?**');
await page.goto(base+'/vinyls/show?id='+id);const info=await page.locator('#vinyl-information').textContent();check(info.includes('Browser edited album')&&info.includes('Browser Edited Producer')&&info.includes('Browser Changed')&&info.includes('2021'),'update fields visible');
await page.goto(base+'/vinyls?q=Browser');const form=page.locator('.delete-vinyl-form').filter({has:page.locator('input[name="id"][value="'+id+'"]')});await form.locator('button').click();check(await page.locator('#delete-record-title').textContent()==='Browser edited album','delete correct album');await page.locator('#delete-cancel').click();check(await form.count()===1,'cancel preserves record');await form.locator('button').click();let posts=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/vinyls/delete'))posts++;});await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/vinyls/delete')),page.locator('#delete-confirm').evaluate(e=>{e.click();e.click();})]);await page.waitForFunction(()=>document.body.textContent.includes('Vinilo eliminado correctamente.'));check(posts===1,'double click sends one delete');check((await page.locator('body').textContent()).includes('Vinilo eliminado correctamente.'),'delete success');const response=await page.goto(base+'/vinyls/show?id='+id);check(response.status()===404,'deleted record absent');check(errors.length===0,'no CRUD javascript errors');console.log('OK: '+checks+' real browser CRUD checks; isolated fictitious database.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
